defaults:
  - eval_base

provider_config:
  name: tapvid3d
  stride: 1
  override_anno: adt_full/megasam
  config:
    data_root: "../sample_data/adt_source"
    split: "full"
    subset: "adt"
    
transform:
  - name: filter_edge
    kwargs: 
      depth_rtol: 0.03
      normal_tol: 5

query_mode: pass_through