defaults:
  - eval_base

provider_config:
  name: dynamic_replica
  stride: 1
  override_anno: null
  config:
    data_root: "../sample_data/dynamic_replica"
    split: "valid"
    max_trajs_per_sample: 256

query_mode: first_visible

transform:
  - name: set_roi
    kwargs: {}