defaults:
  - eval_base

provider_config:
  name: tapvid3d
  stride: 1
  override_anno: drivetrack_full/megasam
  config:
    data_root: "../sample_data/tapvid3d"
    split: "full"
    subset: "drivetrack"
    
transform:
  - name: resize
    kwargs:
      target_hw: [384, 512]
  - name: filter_edge
    kwargs: 
      depth_rtol: 0.3
      normal_tol: 10.0
  - name: set_roi
    kwargs: {}

query_mode: pass_through