defaults:
  - eval_base

provider_config:
  name: lsfodyssey
  stride: 1
  override_anno: null
  config:
    data_root: "../sample_data/LSFOdyssey"
    split: "test"

query_mode: pass_through

transform:
  - name: set_roi
    kwargs: {}