defaults:
  - eval_base

provider_config:
  name: tapvid3d
  stride: 1
  override_anno: pstudio_full/megasam
  config:
    data_root: "../sample_data/tapvid3d"
    split: "full"
    subset: "pstudio"
    
transform:
  - name: filter_edge
    kwargs: 
      depth_rtol: 0.07
      normal_tol: 5

query_mode: pass_through