type: train

seed: 42
resolution: [384, 512]
num_threads: 8
different_seeds_per_epoch: False

traj_sampling:
  traj_mode: "random"
  query_mode: random
  outlier_threshold: 1000000000.0 # in pixels
  min_visible_ratio: 0.00000001
  mask_negative_depth: False

resize:
  mode: "simple_resize" # aug_crop or simple_resize