defaults:
  - kubric_base

epoch_len: 10000000
frames_per_sample: 24

traj_sampling:
  num_traj: 384 # null to keep all trajectories

providers_config:
  - name: kubric
    stride: 1
    weight: 1.0
    override_anno: null
    config:
      data_root: ../sample_data/kubric
      keep_static_prob: 1.0 # no dynamic filter
      dynamic_filter_threshold: 0.1